### ISSUE TITLE
issue with Trigger AHO code

### ISSUE THREAD

**Issue by serge-bakhteiarov** [aws-samples/aws-healthomics-modular-scalable-serverless-orchestration#1]
hello, the lambda which. trigger aho has syntax errors :  
    response = aho.start_run(
        workflowId=aho_workflow_id,
        roleArn: "arn:aws:iam::123456789012:role/AHOrole",  -- : instead of =
        parameters=params,
        outputUri=output_s3_path
        }. -- this bracket?
    )

**Comment by anuj8148** [comment]
Thank you. Fixed it.
